# Generated by Django 6.0.1 on 2026-01-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images'),
        ),
    ]
